//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTable
    {
        public int Table_id { get; set; }
        public string Some_info { get; set; }
    
        public virtual MyTable MyTable1 { get; set; }
        public virtual MyTable MyTable2 { get; set; }
        public virtual MyTable2 MyTable21 { get; set; }
    }
}
